### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by 3buddy** [Krisseck/Detect-CMS#11]
Fatal error: Uncaught Error: Class 'DetectCMS\Systems\Drupal' not found in /home/brightde/brightroots.net/wordpresscheck/DetectCMS/DetectCMS.php:57 Stack trace: #0 /home/brightde/brightroots.net/wordpresscheck/DetectCMS/DetectCMS.php(43): DetectCMS\DetectCMS->check('http://google.c...') #1 /home/brightde/brightroots.net/wordpresscheck/index.php(9): DetectCMS\DetectCMS->__construct('http://google.c...') #2 {main} thrown in /home/brightde/brightroots.net/wordpresscheck/DetectCMS/DetectCMS.php on line 57

what is the issue ?

**Comment by Krisseck** [comment]
It looks like it can't find the different System files. Do you have `Systems` folder in the project does it have several PHP files in it?

**Comment by 3buddy** [comment]
yes i have

**Comment by 3buddy** [comment]
here is the code and the structure 


![screen shot 2018-08-14 at 12 12 56 pm](https://user-images.githubusercontent.com/7742418/44075738-7f6dec36-9fbb-11e8-8264-cf61cde59890.png)
![screen shot 2018-08-14 at 12 11 57 pm](https://user-images.githubusercontent.com/7742418/44075741-80f1a688-9fbb-11e8-9c29-e658868f0272.png)




it is the php code 

<?php

error_reporting(E_ALL);
ini_set('display_errors', 1);


include("DetectCMS/DetectCMS.php");
$domain = "http://google.com";
$cms = new \DetectCMS\DetectCMS($domain);
if($cms->getResult()) {
    echo "Detected CMS: ".$cms->getResult();
} else {
    echo "CMS couldn't be detected";
}



?>

**Comment by 3buddy** [comment]
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
include("DetectCMS/DetectCMS.php");
$domain = "http://google.com";
$cms = new \DetectCMS\DetectCMS($domain);
if($cms->getResult()) {
    echo "Detected CMS: ".$cms->getResult();
} else {
    echo "CMS couldn't be detected";
}
?>

**Comment by 3buddy** [comment]
![screen shot 2018-08-14 at 2 33 30 pm](https://user-images.githubusercontent.com/7742418/44082510-0e6036b6-9fcf-11e8-9898-6c2f20a5fe3e.png)

**Comment by 3buddy** [comment]
please check

**Comment by N1rmod023** [comment]
Hey, I’m having the same issue
Did you find an answer?

**Comment by webxteria** [comment]
@N1rmod023,  I had the issue few days back, I figured out the issue is with file names. These are cases sensitives at some version of php and on some servers. Just rename the file and change the first letter, hope that will work.

**Comment by Giulianoberaldo** [comment]
Hello.i have this error:
`Fatal error: Uncaught Error: Call to undefined function DetectCMS\Systems\str_get_html() in C:\xampp\htdocs\sitecheck\vendor\krisseck\detect-cms\src\DetectCMS\Systems\wordpress.php:35 Stack trace: #0 C:\xampp\htdocs\sitecheck\vendor\krisseck\detect-cms\src\DetectCMS\DetectCMS.php(92): DetectCMS\Systems\Wordpress->readme() #1 C:\xampp\htdocs\sitecheck\vendor\krisseck\detect-cms\src\DetectCMS\DetectCMS.php(46): DetectCMS\DetectCMS->check('clickandstrike....') #2 C:\xampp\htdocs\sitecheck\checksite.php(21): DetectCMS\DetectCMS->__construct('clickandstrike....') #3 {main} thrown in C:\xampp\htdocs\sitecheck\vendor\krisseck\detect-cms\src\DetectCMS\Systems\wordpress.php on line 35`

i have install it on my pc, in localhost. on server, i'll use php 7.4 always the last version.
@Krisseck

**Comment by ffos-user-57** [comment]
@webxteria I still have this issue, what do you mean rename? The files? And the code's content to be something else? Can you explain further

**Comment by ffos-user-57** [comment]
Nevermind i fixed it  - if you are using the latest XAMPP that has PHP 8 (im writing this in Feb 2022) then you can use my example: https://github.com/ffos-user-57/Detect-CMS
