### ISSUE TITLE
Not PHP 7.3 compatible

### ISSUE THREAD

**Issue by rocramer** [Krisseck/Detect-CMS#18]
If upgrading to PHP 7.3 I'm getting the error:

``
Compilation failed: invalid range in character class at offset 4
``

The regular expressions in the `simple_html_dom.php` are not compatible with PHP 7.3. The Hyphen needs to be escaped. See https://ayesh.me/Upgrade-PHP-7.3#pcre2

I would create a PR to change the regex if it is okay for you?

**Comment by daipratt** [comment]
See here for PHP7.3 compatible simple_html_dom.php library:
https://github.com/Kub-AT/php-simple-html-dom-parser
